language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --version && echo && vendor/bin/phpcs -p --standard=PSR2 src tests

after_success:
  - vendor/bin/coveralls -v
